export const ROUTE_TO_PLANT_MASTER = "ROUTE_TO_PLANT_MASTER";
export const ROUTE_TO_USER_ROLE_MASTER = "ROUTE_TO_USER_ROLE_MASTER";
export const ROUTE_TO_EMPLOYEE_MASTER = "ROUTE_TO_EMPLOYEE_MASTER";
export const ROUTE_TO_SUPPLIER_CATEGORY_MASTER =
  "ROUTE_TO_SUPPLIER_CATEGORY_MASTER";
export const ROUTE_TO_CUSTOMER_MASTER = "ROUTE_TO_CUSTOMER_MASTER";
export const ROUTE_TO_SUPPLIER_MASTER = "ROUTE_TO_SUPPLIER_MASTER";
